# From .env:
# I - Image location, e.g. local/protonwire:latest
# S - Sources directory (with Dockerfile, natpmp-info-reporter-service.sh, etc)
# THIS - Runtime location (location of .env, private.key, etc)
# PROTONVPN_SERVER - ProtonVPN server

services:
  protonwire:
    build: "${S}"
    cap_add:
    - NET_ADMIN
    container_name: protonwire
    environment:
      DEBUG: "0"
      KILL_SWITCH: "0"
      PROTONVPN_SERVER: "${PROTONVPN_SERVER}"
      TZ: "Etc/UTC"
    image: "${I}"
    init: true
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "/usr/bin/protonwire check --service --silent || exit 1"]
      interval: 120s
      start_period: 20s
    network_mode: bridge
    #ports:
    #- 127.0.0.1:3000:3000  # Example service to expose to localhost
    restart: never
    sysctls:
    - net.ipv4.conf.all.rp_filter=2
    - net.ipv6.conf.all.disable_ipv6=1
    volumes:
    - type: tmpfs
      target: /tmp
    - type: bind
      source: ${THIS}/private.key
      target: /etc/protonwire/private-key
      read_only: true

  protonwire-natpmpc:
    command: "/usr/bin/protonwire-natpmp.sh"
    container_name: protonwire-natpmpc
    depends_on:
      protonwire:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c"]
    environment:
      TZ: "Etc/UTC"
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "/usr/bin/protonwire-natpmp-healthcheck.sh || exit 1"]
      interval: 120s
      start_period: 23s
    image: "${I}"
    init: true
    network_mode: service:protonwire
    restart: never
    volumes:
    - type: bind
      source: ${S}/protonwire-natpmp.sh
      target: /usr/bin/protonwire-natpmp.sh
    - type: bind
      source: ${S}/protonwire-natpmp-healthcheck.sh
      target: /usr/bin/protonwire-natpmp-healthcheck.sh
    - type: bind
      source: ${S}/protonwire-natpmp-info-reporter-service.sh
      target: /usr/bin/protonwire-natpmp-info-reporter-service.sh
    - type: bind
      source: /tmp/protonwire-natpmpc-log
      target: /log

version: '2.3'
